services:
  codeserver:
    container_name: codeserver-8f448v
    image: adrosar/remote-ide
    tty: false
    stdin_open: false
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - $PWD:/home/coder/workspace/remote-ide
    networks:
      - main
networks:
  main:
    name: net-7hd9fk
    external: false
