services:
  codeserver:
    container_name: codeserver-8f448v
    build:
      context: .
      dockerfile: Dockerfile
    tty: false
    stdin_open: false
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - $PWD/config:/home/coder/.config/code-server
      - $PWD/local:/home/coder/.local/share/code-server
      - $PWD/project:/home/coder/project
    networks:
      - main
networks:
  main:
    name: net-7hd9fk
    external: false
